# Generated by Django 3.2.7 on 2021-09-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebaradditionalannouncements',
            old_name='type1',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='sidebarscheduleofservices',
            old_name='type1',
            new_name='type',
        ),
    ]
