# Generated by Django 3.2.7 on 2021-09-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210912_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchannouncement',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='churchannouncement',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
