# Generated by Django 3.2.7 on 2021-09-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_churchannouncement_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaradditionalannouncements',
            name='display_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sidebarscheduleofservices',
            name='display_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sidebarweeklyschedule',
            name='display_order',
            field=models.IntegerField(null=True),
        ),
    ]
