# Generated by Django 3.2.7 on 2021-09-13 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210912_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchannouncement',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='churchannouncement',
            name='body',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='churchannouncement',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='churchannouncement',
            name='image_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='churchannouncement',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='churchannouncement',
            name='live_stream_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='churchannouncement',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='churchannouncement',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='churchannouncement',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_types', to='main.announcementtype'),
        ),
        migrations.AlterField(
            model_name='sidebaradditionalannouncements',
            name='body',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='sidebarscheduleofservices',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sidebarscheduleofservices',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sidebarscheduleofservices',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_of_services_type', to='main.scheduleofservicestype'),
        ),
        migrations.AlterField(
            model_name='sidebarweeklyschedule',
            name='day',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sidebarweeklyschedule',
            name='service',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='sidebarweeklyschedule',
            name='time',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
