# Generated by Django 3.2.7 on 2021-09-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210912_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchannouncement',
            name='author_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='churchannouncement',
            name='body_ru',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='churchannouncement',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sidebaradditionalannouncements',
            name='body_ru',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='sidebarscheduleofservices',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sidebarweeklyschedule',
            name='day_ru',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sidebarweeklyschedule',
            name='service_ru',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='sidebarweeklyschedule',
            name='time_ru',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
