# Generated by Django 3.2.7 on 2021-09-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210913_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarscheduleofservices',
            name='link_ru',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
